<?php

/**
 * @file
 * stanford_news.module
 */

/**
 * Implements hook_theme().
 */
function stanford_news_theme() {
  return [
    'node__stanford_news__full' => [
      'template' => 'node--stanford-news',
      'base hook' => 'node'
    ],
    'field__node__su_news_topics' => [
      'template' => 'field--node--su-news-topics',
      'base hook' => 'field'
    ],
    'signup_block' => [
      'variables' => [],
      'template' => 'signup-block'
    ]
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function stanford_news_preprocess_block(&$variables) {
  if (!empty($variables['elements']['#id'])) {
    if ($variables['elements']['#id'] == 'newslettersignup') {
      $variables['#attached']['library'][] = 'stanford_news/newsletter_signup';
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function stanford_news_preprocess_node(&$variables) {
  $node = $variables['node'];
  //check content type
  if ($node->getType() == 'stanford_news') {
    $variables['#attached']['library'][] = 'stanford_news/news_node';
  }
}

/**
 * Implements hook_views_pre_view().
 */
function stanford_news_views_pre_view(\Drupal\views\ViewExecutable $view, $display_id, array &$args) {
  if ($view->id() == 'stanford_news_list' && $display_id == 'block_3') {
    //if (isset($args[0])) {
    //$display_handler = $view->display_handler();
    //kint($display_handler);
      //$filters = $view->display_handler->getOption('filters');
      //kint($filters);
//      if ($filters['field_filter']) {
//        foreach ($filters['field_filter']['value'] as $key => $filter) {
//          unset($filters['field_filter']['value'][$key]);
//        }
//      }
//      $view->display_handler->overrideOption('filters', $filters);
  }

}
