<?php

/**
 * @file
 * stanford_news.module
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function stanford_news_theme() {
  return [
    'node__stanford_news__full' => [
      'template' => 'node--stanford-news',
      'base hook' => 'node'
    ],
    'field__node__su_news_topics' => [
      'template' => 'field--node--su-news-topics',
      'base hook' => 'field'
    ],
    'signup_block' => [
      'variables' => [
        'configuration' => [],
      ],
      'template' => 'signup-block'
    ],
    'block__menu_block__news_topics' => [
      'template' => 'block--menu-block--news-topics',
      'base hook' => 'block'
    ]
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function stanford_news_preprocess_block(&$variables) {

  // Attach Library to the signup block wherever it goes.
  if (!empty($variables['elements']['#id'])) {
    if ($variables['elements']['#id'] == 'newslettersignup') {
      $variables['#attached']['library'][] = 'stanford_news/newsletter_signup';
    }
  }

  // Attach library to news_list block.
  if (!empty($variables['elements']['content']['#cache']['contexts'])) {
    if (in_array('route.menu_active_trails:news-topics', $variables['elements']['content']['#cache']['contexts'])) {
      $variables['#attached']['library'][] = 'stanford_news/news_list';
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function stanford_news_preprocess_node(&$variables) {
  $node = $variables['node'];
  //check content type
  if ($node->getType() == 'stanford_news') {
    $variables['#attached']['library'][] = 'stanford_news/news_node';
  }
}
